apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adp-portal
  description: Default Application used for techdocs
  # Example for optional annotations
  annotations:
    github.com/project-slug: defra-adp-sandpit/adp-portal
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ffc-demo-claim-service"
  description: |
    Digital service mock to claim public money in the event property subsides into mine shaft. 
    The claim service receives claim data and if doesn't already exist saves it in a PostgreSQL database table. 
    It also publishes events to message queues that a new claim has been received.
  annotations:
    github.com/project-slug: DEFRA/ffc-demo-claim-service
    dev.azure.com/project: DEFRA-FFC
    dev.azure.com/build-definition: DEFRA.ffc-demo-claim-service
    sonarqube.org/project-key: adp-ffc-demo-claim-service
    grafana/dashboard-selector: "folderTitle == 'Managed Prometheus'"
    backstage.io/techdocs-entity: component:default/adp-portal
  tags:
    - node
    - service-bus
    - private
    - back-end
    - database
spec:
  type: backend
  lifecycle: beta
  owner: "group:default/fcp-demo"
  system: fcp-demo-service
  dependsOn:
    - "resource:default/fcp-demo-claim-queue"
    - "resource:default/fcp-demo-calculation-queue"
    - "resource:default/fcp-demo-schedule-topic"
    - "resource:default/fcp-demo-claim-database"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fcp-demo-claim-database
  description: Database for persisting claims from users.
  tags:
    - postgresql
spec:
  type: database
  owner: "group:default/fcp-demo"
  system: fcp-demo-service
  dependsOn:
    - "resource:default/adpdbsps01"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fcp-demo-calculation-queue
  description: Calculation message queue
  tags:
    - azure-service-bus
    - queue
spec:
  type: message-queue
  owner: "group:default/fcp-demo"
  system: fcp-demo-service
  dependsOn:
    - "resource:default/ADPINFSB01"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fcp-demo-schedule-topic
  description: Schedules message topic
  tags:
    - azure-service-bus
    - topic
spec:
  type: message-topic
  owner: "group:default/fcp-demo"
  system: fcp-demo-service
  dependsOn:
    - "resource:default/ADPINFSB01"
