version: '3.4'
services:
  mine-support-claim-service:
    build: .
    image: mine-support-claim-service
    container_name: mine-support-claim-service
    depends_on:
      - mine-support-postgres-claims
    environment:
      POSTGRES_DB: mine_claims
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: mine-support-postgres-claims
      POSTGRES_PORT: 5432
    ports:
      - "80:3003"

  mine-support-postgres-claims:
    container_name: mine-support-postgres-claims
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: mine_claims
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
