version: '3.7'

# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  ffc-demo-claim-service:
    build:
      context: .
      target: development
    ports:
      - "3003:3003"

  ffc-demo-claim-postgres:
    ports:
      - "5432:5432"
