version: '3.7'

services:
  ffc-demo-claim-service:
    build:
      context: .
      target: production
      args:
        REGISTRY: ${DOCKER_REGISTRY}
    image: ffc-demo-claim-service
    depends_on:
      - ffc-demo-claim-postgres
    env_file:
      - variables/message-queues.env
      - variables/postgres.env
    environment:
      POSTGRES_HOST: ffc-demo-claim-postgres
      POSTGRES_PORT: 5432
      CALCULATION_QUEUE_NAME: calculation
      CALCULATION_QUEUE_URL: http://ffc-demo-claim-message-queue:9324/queue/calculation
      CREATE_CALCULATION_QUEUE: "true"
      CALCULATION_ENDPOINT: http://ffc-demo-claim-message-queue:9324
      DEV_ACCESS_KEY_ID: elasticmq
      DEV_ACCESS_KEY: elasticmq
      SCHEDULE_QUEUE_NAME: schedule
      SCHEDULE_QUEUE_URL: http://ffc-demo-claim-message-queue:9324/queue/schedule
      CREATE_SCHEDULE_QUEUE: "true"
      SCHEDULE_ENDPOINT: http://ffc-demo-claim-message-queue:9324
    volumes:
      - ./server/:/home/node/server/
      - ./scripts/:/home/node/scripts/
      - ./index.js:/home/node/index.js
      - ./package.json:/home/node/package.json

  ffc-demo-claim-postgres:
    image: postgres:11.4-alpine
    env_file:
      - variables/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ffc-demo-claim-message-queue:
    image: softwaremill/elasticmq

volumes:
  postgres_data: {}
  node_modules: {}
