version: '3'
services:
  mine-support-claim-service:
    build: .
    image: mine-support-claim-service
    container_name: mine-support-claim-service
    command: sh -c "npx wait-on -v tcp:mine-support-claim-postgres:5432 && npm run migrate && npm run start:watch"
    depends_on:
      - mine-support-claim-postgres
    environment:
      POSTGRES_DB: mine_claims
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: mine-support-claim-postgres
      POSTGRES_PORT: 5432
      MESSAGE_QUEUE_HOST : "amq"
      MESSAGE_QUEUE_PORT : "5672"
      CALCULATION_QUEUE_ADDRESS : "calculation"
      CALCULATION_QUEUE_USER : "artemis"
      CALCULATION_QUEUE_PASSWORD : "artemis"
      SCHEDULE_QUEUE_ADDRESS : "payment"
      SCHEDULE_QUEUE_USER : "artemis"
      SCHEDULE_QUEUE_PASSWORD : "artemis"
    networks:
      - claim-postgres
      - amq

  mine-support-claim-postgres:
    container_name: mine-support-claim-postgres
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: mine_claims
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    networks:
      - claim-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  amq:
    image: vromero/activemq-artemis:latest-alpine
    ports:
    - "8161:8161"
    - "5672:5672"
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
    networks:
      - amq
networks:
  claim-postgres: {}
  amq: {}

volumes:
  postgres_data:
