version: '3'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-demo-claim-service:
    command: npm run test
    image: ffc-demo-claim-service-test
    container_name: ffc-demo-claim-service-test
    volumes:
      - ./.git:/usr/src/app/.git
      - ./test-output:/usr/src/app/test-output

  ffc-demo-claim-postgres:
    container_name: ffc-demo-claim-postgres-test
