version: '3.7'

services:
  ffc-demo-claim-service:
    build:
      context: .
      target: production
    image: ffc-demo-claim-service
    depends_on:
      - ffc-demo-claim-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-demo-claim-service-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      CALCULATION_QUEUE_ADDRESS: ${CALCULATION_QUEUE_ADDRESS:-notset}
      CLAIM_QUEUE_ADDRESS: ${CLAIM_QUEUE_ADDRESS:-notset}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      POSTGRES_DB: ${POSTGRES_DB:-ffc_demo_claim}
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-demo-claim-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      SCHEDULE_QUEUE_ADDRESS: ${SCHEDULE_QUEUE_ADDRESS:-notset}
      SEND_TIMEOUT_IN_SECONDS: 10
    volumes:
      - ./app/:/home/node/app/
      - ./test/:/home/node/test/
      - ./scripts/:/home/node/scripts/
      - ./package.json:/home/node/package.json

  ffc-demo-claim-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_demo_claim
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: {}
  node_modules: {}
