version: '3'

# This override file should be used in development environments to
# bind-mount the app from the host into the container

services:
  mine-support-claim-service:
    command: >
      sh -c "
        scripts/wait-for/wait-for mine-support-claim-postgres:5432 --
        npm run migrate &&
        npm run start:watch"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  node_modules:
