version: '3.7'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-demo-claim-service:
    build:
      context: .
      target: development
    command: >
      sh -c "npm run test"
    environment:
      NOTIFY_API_KEY: test-key
      PACT_BROKER_BASE_URL: ${PACT_BROKER_BASE_URL:-notset}
    volumes:
      - ./app/:/home/node/app/
      - ./test/:/home/node/test/
      - ./scripts/:/home/node/scripts/
      - ./package.json:/home/node/package.json
      - ./test-output/:/home/node/test-output/
      - ./jest.config.js:/home/node/jest.config.js
      - ./jest.setup.js:/home/node/jest.setup.js
