version: '3'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  mine-support-claim-service:
    volumes:
      - ./test-output:/home/node/test-output
