version: '3'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-demo-claim-service:
    command: npm run test
    container_name: ffc-demo-claim-service-test-${BUILD_NUMBER:-local}

  ffc-demo-claim-postgres:
    container_name: ffc-demo-claim-postgres-test-${BUILD_NUMBER:-local}
