version: '3'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-demo-claim-service:
    command: npm run test
    volumes:
      - ./.git:/usr/src/app/.git
      - ./test-output:/usr/src/app/test-output
