version: '3'
services:
  mine-support-claim-service:
    build: .
    image: mine-support-claim-service
    container_name: mine-support-claim-service
    depends_on:
      - mine-support-claim-postgres
    environment:
      POSTGRES_DB: mine_claims
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: mine-support-claim-postgres
      POSTGRES_PORT: 5432
    networks:
      - claim-postgres
    ports:
      - "3003:3003"

  mine-support-claim-postgres:
    container_name: mine-support-claim-postgres
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: mine_claims
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    networks:
      - claim-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  claim-postgres: {}

volumes:
  postgres_data:
