version: '3.7'

services:
  ffc-demo-claim-service:
    build:
      context: .
      target: production
    image: ffc-demo-claim-service
    depends_on:
      - ffc-demo-claim-postgres
    env_file:
      - variables/postgres.env
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-demo-claim-service-local
      APPINSIGHTS_INSTRUMENTATIONKEY:
      POSTGRES_HOST: ffc-demo-claim-postgres
      POSTGRES_PORT: 5432
      MESSAGE_QUEUE_HOST: ffc-demo-claim-message-queue
      MESSAGE_QUEUE_PORT: 5672
      CALCULATION_QUEUE_ADDRESS: calculation
      CALCULATION_QUEUE_USER: artemis
      CALCULATION_QUEUE_PASSWORD: artemis
      SCHEDULE_QUEUE_ADDRESS: schedule
      SCHEDULE_QUEUE_USER: artemis
      SCHEDULE_QUEUE_PASSWORD: artemis
      SEND_TIMEOUT_IN_SECONDS: 10
      CLAIM_QUEUE_ADDRESS: claim
      CLAIM_QUEUE_USER: artemis
      CLAIM_QUEUE_PASSWORD: artemis
    volumes:
      - ./server/:/home/node/server/
      - ./test/:/home/node/test/
      - ./scripts/:/home/node/scripts/
      - ./index.js:/home/node/index.js
      - ./package.json:/home/node/package.json

  ffc-demo-claim-postgres:
    image: postgres:11.4-alpine
    env_file:
      - variables/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: {}
  node_modules: {}
