version: '3'

# This override file should be used in development environments to
# connect this service to sibling services from other repositories

services:
  ffc-demo-claim-service:
    networks:
      - ffc-demo

networks:
  ffc-demo:
    external: true
