version: '3'
services:
  mine-support-claim-service:
    build: .
    image: mine-support-claim-service
    container_name: mine-support-claim-service
    command: npm run watch:server
    ports:
      - "3003:3003"
    volumes:
      - node_modules:/mine-support-claim-service/node_modules
      - .:/mine-support-claim-service

volumes:
  node_modules:
