version: '3'

# This file should be used when running automated tests so that test
# output is saved to the host.

services:
  ffc-demo-claim-test:
    build: .
    image: ffc-demo-claim-test
    container_name: ffc-demo-claim-test
    command: npm run test
    depends_on:
      - ffc-demo-claim-test-postgres
    env_file:
      - variables/postgres.env
    environment:
      POSTGRES_HOST: ffc-demo-claim-test-postgres
    networks:
      - ffc-demo-claim-test
    volumes:
      - .:/usr/src/app
      - test-node_modules:/usr/src/app/node_modules

  ffc-demo-claim-test-postgres:
    container_name: ffc-demo-claim-test-postgres
    image: postgres:11.4-alpine
    env_file:
      - variables/postgres.env
    networks:
      - ffc-demo-claim-test
    volumes:
      - test-postgres-data:/var/lib/postgresql/data

networks:
  ffc-demo-claim-test: {}

volumes:
  test-node_modules: {}
  test-postgres-data: {}
