version: '3'

services:
  ffc-demo-claim-service:
    build: .
    image: ffc-demo-claim-service
    depends_on:
      - ffc-demo-claim-postgres
    env_file:
      - variables/message-queues.env
      - variables/postgres.env
    environment:
      POSTGRES_HOST: ffc-demo-claim-postgres
      POSTGRES_PORT: 5432
      MESSAGE_QUEUE_HOST : host.docker.internal
      MESSAGE_QUEUE_PORT : 5672
    networks:
      - ffc-demo-claim
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

  ffc-demo-claim-postgres:
    image: postgres:11.4-alpine
    env_file:
      - variables/postgres.env
    networks:
      - ffc-demo-claim

networks:
  ffc-demo-claim: {}

volumes:
  node_modules: {}
