version: '3'

# This override file should be used in development environments to
# bind-mount the app from the host into the container

services:
  mine-support-claim-service:
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  node_modules:
