version: '3.7'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-demo-claim-service:
    build:
      context: .
      target: development
    command: >
      sh -c "
        scripts/wait-for/wait-for ffc-demo-claim-postgres:5432 --
        scripts/wait-for/wait-for ffc-demo-claim-message-queue:9324 --
        npm run migrate &&
        npm run test"
    volumes:
      - ./test/:/home/node/test/
      - ./test-output/:/home/node/test-output/
      - ./jest.config.js:/home/node/jest.config.js
    depends_on:
      - ffc-demo-claim-message-queue

