version: '3.7'

# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  ffc-demo-claim-service:
    build:
      context: .
      target: development
    ports:
      - "9229:9229"

  ffc-demo-claim-postgres:
    ports:
      - "5432:5432"
