version: '3.7'

# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  ffc-demo-claim-service:
    build:
      context: .
      target: development
    command: >
      sh -c "
        scripts/wait-for/wait-for ffc-demo-claim-postgres:5432 --
        scripts/wait-for/wait-for ffc-demo-claim-message-queue:5672 --
        npm run migrate &&
        npm run start:watch"
    ports:
      - "3003:3003"

  ffc-demo-claim-postgres:
    ports:
      - "5432:5432"

  ffc-demo-claim-message-queue:
    ports:
      - "8161:8161"
      - "5672:5672"
      