version: '3'

# This override file should be used in development environments to
# connect this service to sibling services from other repositories

services:
  ffc-demo-claim-service:
    command: >
      sh -c "
        scripts/wait-for/wait-for ffc-demo-claim-postgres:5432 --
        scripts/wait-for/wait-for ffc-demo-message-queue:8161 --
        npm run migrate &&
        npm run start:watch"
    networks:
      - ffc-demo
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

networks:
  ffc-demo:
    external: true

volumes:
  node_modules: {}
