version: '3.7'

services:
  ffc-demo-claim-service:
    build: .
    image: ffc-demo-claim-service
    depends_on:
      - ffc-demo-claim-postgres
    env_file:
      - variables/message-queues.env
      - variables/postgres.env
    environment:
      POSTGRES_HOST: ffc-demo-claim-postgres
      POSTGRES_PORT: 5432
      CALCULATION_ENDPOINT: http://ffc-demo-claim-message-queue:9324
      CALCULATION_QUEUE_URL: http://ffc-demo-claim-message-queue:9324/queue/calculation
      CALCULATION_QUEUE_ACCESS_KEY_ID: elasticmq
      CALCULATION_QUEUE_ACCESS_KEY: elasticmq
      SCHEDULE_ENDPOINT: http://ffc-demo-claim-message-queue:9324
      SCHEDULE_QUEUE_URL: http://ffc-demo-claim-message-queue:9324/queue/schedule
      SCHEDULE_QUEUE_ACCESS_KEY_ID: elasticmq
      SCHEDULE_QUEUE_ACCESS_KEY: elasticmq
    volumes:
      - ./server/:/usr/src/app/server/
      - ./scripts/:/usr/src/app/scripts/
      - ./index.js:/usr/src/app/index.js
      - ./package.json:/usr/src/app/package.json

  ffc-demo-claim-postgres:
    image: postgres:11.4-alpine
    env_file:
      - variables/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ffc-demo-claim-message-queue:    
    image: softwaremill/elasticmq
    ports:
      - "9324:9324"

volumes:
  postgres_data: {}
  node_modules: {}
