version: '3.7'

services:
  ffc-demo-claim-service:
    build:
      context: .
      target: production
    image: ffc-demo-claim-service
    depends_on:
      - ffc-demo-claim-postgres
    env_file:
      - variables/postgres.env
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-demo-claim-service-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      CALCULATION_QUEUE_ADDRESS: ffc-demo-calculation-${MESSAGE_QUEUE_SUFFIX}
      CLAIM_QUEUE_ADDRESS: ffc-demo-claim-${MESSAGE_QUEUE_SUFFIX}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      POSTGRES_PORT: 5432
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-demo-claim-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      SCHEDULE_QUEUE_ADDRESS: ffc-demo-schedule-${MESSAGE_QUEUE_SUFFIX}
      SEND_TIMEOUT_IN_SECONDS: 10
    volumes:
      - ./server/:/home/node/server/
      - ./test/:/home/node/test/
      - ./scripts/:/home/node/scripts/
      - ./index.js:/home/node/index.js
      - ./package.json:/home/node/package.json

  ffc-demo-claim-postgres:
    image: postgres:11.4-alpine
    env_file:
      - variables/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: {}
  node_modules: {}
