apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.component: {{ .Values.containers.service.name }}
  name: {{ .Values.containers.service.name }}
spec:
  replicas: {{ .Values.replicas }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy: {}
  template:
    metadata:
      labels:
        app.component: {{ .Values.containers.service.name }}
    spec:
      containers:   
      - name: {{ .Values.containers.service.name }}
        image: {{ if .Values.containers.service.registry }}{{ .Values.containers.service.registry }}/{{ end }}{{ .Values.containers.service.image }}:{{ .Values.containers.service.tag }}
        imagePullPolicy: {{ .Values.containers.service.imagePullPolicy }}
        env:                
        - name: NODE_ENV
          value: {{ .Values.environment }}
        - name: POSTGRES_USERNAME
          value: {{ .Values.postgresUsername }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresPassword }}
        - name: MINE_SUPPORT_MESSAGE_QUEUE
          value: {{ .Values.containers.service.messageQueue }}
        ports:
        - containerPort: {{ .Values.containers.service.port }}
        command: ["/bin/sh","-c"]
        args: ["sequelize db:migrate; node index"]
        resources:
          requests:
            memory: {{ .Values.containers.service.requestMemory | quote }}
            cpu: {{ .Values.containers.service.requestCpu | quote }}
          limits:
            memory: {{ .Values.containers.service.limitMemory | quote }}
            cpu: {{ .Values.containers.service.limitCpu | quote }}
        volumes:                      
      restartPolicy: {{ .Values.containers.service.restartPolicy }}
status: {}
