#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

(
  cd "${projectRoot}"

  helm delete --purge \
    mine-support-claim-artemis \
    mine-support-claim-postgres \
    mine-support-claim-service
)
