#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

# Set expected prefix for Docker resource names managed by this script
dockerPrefix="ffc-demo-claim"

(
  cd "${projectRoot}"

  helm delete --purge \
    ${dockerPrefix}-artemis \
    ${dockerPrefix}-postgres \
    ${dockerPrefix}-service
)
