#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

# Set expected prefix for Docker resource names managed by this script
dockerPrefix="ffc-demo-claim"
kubernetesNamespace="ffc-demo"

(
  cd "${projectRoot}"

  echo "Deploying claim message broker"
  helm repo add activemq-artemis https://mailrucloudsolutions.github.io/activemq-artemis-helm/
  helm upgrade \
    --atomic \
    --install \
    --namespace ${kubernetesNamespace} \
    --values helm/ffc-demo-claim-service/artemis-values.yaml \
    --wait \
    ${dockerPrefix}-artemis \
    activemq-artemis/activemq-artemis

  echo "Deploying claim PostgreSQL"
  helm upgrade \
    --atomic \
    --install \
    --namespace ${kubernetesNamespace} \
    --values helm/ffc-demo-claim-service/postgres-values.yaml \
    --wait \
    ${dockerPrefix}-postgres \
    stable/postgresql

  echo "Deploying claim service"
  helm upgrade \
    --atomic \
    --install \
    --namespace ${kubernetesNamespace} \
    --values helm/ffc-demo-claim-service/development-values.yaml \
    --wait \
    ${dockerPrefix}-service \
    ./helm/ffc-demo-claim-service
)
