#!/bin/bash
echo "\n Current working directory"
echo $(pwd)
cd /liquibase
echo "\n File permissions on liquibase dir"
echo $(ls -l)
echo "\n List all files on liquibase dir"
echo $(find $(pwd))
echo "\n Stat on scripts"
echo $(stat scripts)
cd scripts
echo "\n File permissions on scripts dir"
echo $(ls -l)
echo "\n Change dir to liquibase"
cd /liquibase
SCHEMA_PASSWORD=$1
echo "db update on $POSTGRES_HOST $SCHEMA_NAME as $SCHEMA_USERNAME"
scripts/postgres-wait && /liquibase/liquibase \
--driver=org.postgresql.Driver \
--changeLogFile=/changelog/db.changelog.xml \
--url=jdbc:postgresql://$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB \
--username="$SCHEMA_USERNAME" --password="$SCHEMA_PASSWORD" --defaultSchemaName="$SCHEMA_NAME" \
update
