{{- define "ffc-demo-claim-service.container" -}}
name: {{ quote .Values.name }}
env:
- name: NODE_ENV
  value: {{ quote .Values.environment }}
- name: POSTGRES_USERNAME
  value: {{ quote .Values.postgresService.postgresUsername }}
- name: POSTGRES_PASSWORD
  value: {{ quote .Values.postgresService.postgresPassword }}
- name: POSTGRES_DB
  value: {{ quote .Values.postgresService.postgresDatabase }}
- name: POSTGRES_HOST
  value: {{ quote .Values.postgresService.postgresHost }}
- name: POSTGRES_PORT
  value: {{ quote .Values.postgresService.postgresPort }}
- name: MESSAGE_QUEUE_HOST
  value: {{ quote .Values.container.messageQueueHost }}
- name: MESSAGE_QUEUE_PORT
  value: {{ quote .Values.container.messageQueuePort }}
- name: MESSAGE_QUEUE_TRANSPORT
  value: {{ quote .Values.container.messageQueueTransport }}
- name: CALCULATION_QUEUE_ADDRESS
  value: {{ quote .Values.container.calculationQueueName }}
- name: CALCULATION_QUEUE_USER
  value: {{ quote .Values.container.calculationQueueUser }}
- name: CALCULATION_QUEUE_PASSWORD
  value: {{ quote .Values.container.calculationQueuePassword }}
- name: SCHEDULE_QUEUE_ADDRESS
  value: {{ quote .Values.container.calculationQueueName }}
- name: SCHEDULE_QUEUE_USER
  value: {{ quote .Values.container.calculationQueueUser }}
- name: SCHEDULE_QUEUE_PASSWORD
  value: {{ quote .Values.container.calculationQueuePassword }}
- name: CLAIM_QUEUE_ADDRESS
  value: {{ quote .Values.container.calculationQueueName }}
- name: CLAIM_QUEUE_USER
  value: {{ quote .Values.container.calculationQueueUser }}
- name: CLAIM_QUEUE_PASSWORD
  value: {{ quote .Values.container.calculationQueuePassword }}
- name: PORT
  value: {{ quote .Values.container.port }}
livenessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.livenessProbe) | nindent 4}}
readinessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.readinessProbe) | nindent 4}}
ports:
- containerPort: {{ .Values.container.port }}
{{- end -}}
