{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-claim-service.container-secret") -}}
{{- define "ffc-demo-claim-service.container-secret" -}}
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresService.postgresPassword | quote }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUsername | quote }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
{{- end -}}
