{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-claim-service.container-secret") -}}
{{- define "ffc-demo-claim-service.container-secret" -}}
stringData:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  MESSAGE_QUEUE_PASSWORD: {{ .Values.container.messageQueuePassword | quote }}
  MESSAGE_QUEUE_USER: {{ .Values.container.messageQueueUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresService.postgresPassword | quote }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUsername | quote }}
{{- end -}}
