{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-claim-service.container-secret") -}}
{{- define "ffc-demo-claim-service.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUser | quote }}
  {{- if .Values.container.notifyApiKey }}
  NOTIFY_API_KEY: {{ quote .Values.container.notifyApiKey }}
  {{- end }}
  {{- if .Values.container.notifyEmailTemplateKey }}
  NOTIFY_EMAIL_TEMPLATE_KEY: {{ quote .Values.container.notifyEmailTemplateKey }}
  {{- end }}
{{- end -}}
