{{- include "ffc-helm-library.container-secret" (list . "ffc-demo-claim-service.container-secret") -}}
{{- define "ffc-demo-claim-service.container-secret" -}}
stringData:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUsername | quote }}
{{- end -}}
