{{- include "ffc-helm-library.deployment" (list . "ffc-demo-claim-service.deployment") -}}
{{- define "ffc-demo-claim-service.deployment" -}}
spec:
  template:
    metadata:
      labels:
        aapodidbinding: demo
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-demo-claim-service.container") }}
{{- end -}}
