{{- include "ffc-helm-library.deployment" (list . "ffc-demo-claim-service.deployment") -}}
{{- define "ffc-demo-claim-service.deployment" -}}
spec:
  template:
    metadata:
      labels:
        aadpodidbinding: claim-service-demo-identity-binding
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-demo-claim-service.container") }}
{{- end -}}
