apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ quote .Values.name }}
spec:
  replicas: {{ quote .Values.replicaCount }}
  minReadySeconds: {{ quote .Values.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ quote .Values.maxSurge }}
      maxUnavailable: {{ quote .Values.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ quote .Values.name }}
        environment: {{ quote .Values.environment }}
      annotations:
        redeployOnChange: {{ quote .Values.container.redeployOnChange }}
    spec:
      restartPolicy: {{ quote .Values.container.restartPolicy }}
      {{- if quote .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ quote .Values.imagePullSecret }}
      {{- end }}
      containers:
        - name: {{ quote .Values.name }}
          image: {{ quote .Values.image }}
        {{- if quote .Values.container.command }}
        {{- with quote .Values.container.command }}
          command:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with quote .Values.container.args }}
          args:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}
          imagePullPolicy: {{ quote .Values.container.imagePullPolicy }}
          securityContext:
            runAsUser: {{ quote .Values.container.runAsUser }}
            runAsNonRoot: {{ quote .Values.container.runAsNonRoot }}
            readOnlyRootFilesystem: {{ quote .Values.container.readOnlyRootFilesystem }}
            allowPrivilegeEscalation: {{ quote .Values.container.allowPrivilegeEscalation }}
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          resources:
            requests:
                memory: {{ quote .Values.container.requestMemory }}
                cpu: {{ quote .Values.container.requestCpu }}
            limits:
                memory: {{ quote .Values.container.limitMemory }}
                cpu: {{ quote .Values.container.limitCpu }}
          env:
            - name: NODE_ENV
              value: {{ quote .Values.environment }}
            - name: POSTGRES_USERNAME
              value: {{ quote .Values.postgresUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ quote .Values.postgresPassword }}
            - name: POSTGRES_DB
              value: {{ quote .Values.postgresDatabase }}
            - name: POSTGRES_HOST
              value: {{ quote .Values.postgresHost }}
            - name: POSTGRES_PORT
              value: {{ quote .Values.postgresPort }}
            - name: MESSAGE_QUEUE_HOST
              value: {{ quote .Values.container.messageQueueHost }}
            - name: MESSAGE_QUEUE_PORT
              value: {{ quote .Values.container.messageQueuePort }}
            - name: MESSAGE_QUEUE_TRANSPORT
              value: {{ quote .Values.container.messageQueueTransport }}
            - name: CALCULATION_QUEUE_ADDRESS
              value: {{ quote .Values.container.calculationQueueAddress }}
            - name: CALCULATION_QUEUE_USER
              value: {{ quote .Values.container.calculationQueueUser }}
            - name: CALCULATION_QUEUE_PASSWORD
              value: {{ quote .Values.container.calculationQueuePassword }}
            - name: SCHEDULE_QUEUE_ADDRESS
              value: {{ quote .Values.container.scheduleQueueAddress }}
            - name: SCHEDULE_QUEUE_USER
              value: {{ quote .Values.container.scheduleQueueUser }}
            - name: SCHEDULE_QUEUE_PASSWORD
              value: {{ quote .Values.container.scheduleQueuePassword }}
            - name: PORT
              value: "3003"
          livenessProbe:
            httpGet:
              path: {{ quote .Values.livenessProbe.path }}
              port: {{ quote .Values.livenessProbe.port }}
            initialDelaySeconds: {{ quote .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ quote .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ quote .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ quote .Values.readinessProbe.path }}
              port: {{ quote .Values.readinessProbe.port }}
            initialDelaySeconds: {{ quote .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ quote .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ quote .Values.readinessProbe.failureThreshold }}
status: {}
