{{- include "ffc-helm-library.deployment" (list . "ffc-demo-claim-service.deployment") -}}
{{- define "ffc-demo-claim-service.deployment" -}}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-demo-claim-service.container") }}
{{- end -}}
