namespace: ffc-demo
namespaceQueues:
  - name: claim
    owner: 'no'
    roleAssignments:
      - roleName: 'QueueReceiver'
  - name: calculation
    roleAssignments:
      - roleName: 'QueueSender'

namespaceTopics:
  - name: schedule   
    roleAssignments:
      - roleName: 'TopicSender'

postgres:
  db:
    name: claim 
    charset: UTF8
    collation: en_US.utf8

storageAccounts:
  - name: asodemost01
    blobContainers:  
      - name: container-01
    tables:  
      - name: table01
  - name: asodemost02