namespace: ffc-demo

subscriptionId: "55f3b8c6-6800-41c7-a40d-2adb5e4e1bd1"
serviceBusResourceGroupName: sndadpinfrg1401
serviceBusNamespaceName: sndadpinfsb1401

asoAnnotations:
  serviceoperator.azure.com/reconcile-policy: manage

namespaceQueues:
  - name: payment
  - name: calculation
  - name: claim

namespaceTopics:
  - name: schedule   

postgresResourceGroupName: sndadpdbsrg1401
postgresServerName: sndadpdbsps1401
postgres:
  db:
    name: ffc-demo-claim 
    charset: UTF8
    collation: en_US.utf8