namespace: ffc-demo

subscriptionId: 
serviceBusResourceGroupName: sndadpinfrg1401
serviceBusNamespaceName: sndadpinfsb1401

asoAnnotations:
  serviceoperator.azure.com/reconcile-policy: manage

namespaceQueues:
  - name: payment
  - name: calculation

namespaceTopics:
  - name: schedule   

postgresResourceGroupName: sndadpdbsrg1401
postgresServerName: sndadpdbsps1401
postgres:
  db:
    name: claim 
    charset: UTF8
    collation: en_US.utf8