namespaceQueues:
  - name: claim
    owner: 'no'
    roleAssignments:
      - roleName: 'QueueReceiver'
  - name: calculation
    roleAssignments:
      - roleName: 'QueueSender'

namespaceTopics:
  - name: schedule   
    roleAssignments:
      - roleName: 'TopicSender'

postgres:
  db:
    name: claim 
    charset: UTF8
    collation: en_US.utf8
