environment: development
name: ffc-demo-claim-service
namespace: ffc-demo
workstream: ffc-demo
image: ffc-demo-claim-service

labels: {}

appInsights:
  key: 

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  imagePullSecret:

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 200Mi
  limitCpu: 200m
  port: 3003
  calculationQueueAddress: calculation
  claimQueueAddress: claim
  messageQueueHost: myservicebus.servicebus.windows.net
  scheduleTopicAddress: schedule
  appInsightsConsoleDebugEnabled: true
  notifyApiKey:
  notifyEmailTemplateKey:

postgresService:
  postgresDb: ffc_demo_claim
  postgresqlHost: ffc-demo-claims-postgres
  postgresSchema: public
  postgresUser: Demo-Calculation-Service-MI
  postgresPort: 5432

livenessProbe:
  path: /healthz
  port: 3003
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3003
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

aadWorkloadIdentity: true

serviceAccount:
  name: ffc-demo
  roleArn: true

containerConfigMap:
  name: 'ffc-demo-claim-service-config-map'
  configServiceUrl: 'https://sndadpinfac1401.azconfig.io'
  auth:
    workloadIdentity:
      clientId: e9badf28-ce66-4dd3-97e1-e28bfb1da26b
  keyValues:
    labelFilter: 'ffc-demo-claim-service'
    refresh:
      interval: 2m
      monitorKey: 'Sentinel'
      monitorLabel: 'ffc-demo-claim-service'
    keyVaults:
      secretName: ffc-demo-claim-service-container-secret
      refresh:
        interval: 2m

managedIdPrefix: sndadpinfmid1401
userAssignedIdentity:
  managedIdName: ffc-demo-services
