environment: development
name: ffc-demo-claim-service
namespace: ffc-demo
workstream: ffc-demo
image: ffc-demo-claim-service

labels: {}

appInsights:
  key:

azureIdentity:
  resourceID: not-a-real-resourceID
  clientID: not-a-real-clientID

containerConfigMap:
  name: ffc-demo-claim-service-config-map

containerSecret:
  name: ffc-demo-claim-service-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:
  runAsNonRoot: true
  runAsUser: 1000

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 120Mi
  limitCpu: 120m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  port: 3003
  calculationQueueAddress: calculation
  claimQueueAddress: claim
  messageQueueHost: myservicebus.servicebus.windows.net
  scheduleQueueAddress: schedule
  appInsightsConsoleDebugEnabled: true
postgresService:
  postgresDb: ffc_demo_claim
  # postgresHost is the host name of the PostgreSQL service
  postgresHost: ffc-demo-claims-postgres
  postgresSchema: public
  postgresUser: postgres
  # postgresExternalName is the external host name to which PostgreSQL
  # requests should be forwarded. If empty, PostgreSQL is assumed to be
  # within the cluster and accessible via postgresHost
  postgresExternalName:
  postgresPort: 5432

livenessProbe:
  path: /healthz
  port: 3003
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3003
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
