name: ffc-demo-claim-service
namespace: ffc-demo
image: ffc-demo-claim-service

labels: {}

deployment:
  priorityClassName: low
  minReadySeconds: 5

container:
  memCpuTier: CUSTOM
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 200Mi
  limitCpu: 200m
  port: 3003

livenessProbe:
  path: /healthz
  port: 3003
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3003
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

aadWorkloadIdentity: true

serviceAccount:
  name: ffc-demo
  roleArn: true