environment: development
name: ffc-demo-claim-service
namespace: ffc-demo
workstream: ffc-demo
image: ffc-demo-claim-service

labels:
  instance:
  version: 1.0.0

serviceAccount:
  name: ffc-demo-claim-service-account
  roleArn:

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 120Mi
  limitCpu: 120m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  port: 3003
  command: ["/bin/sh","-c"]
  args: ["npm --no-update-notifier run migrate && node index"]
  calculationQueueName: calculation
  calculationQueueEndpoint: http://ffc-demo-claim-message-queue:9324
  calculationQueueRegion: eu-west-2
  calculationCreateQueue: false
  scheduleQueueName: schedule
  scheduleQueueEndpoint: http://ffc-demo-claim-message-queue:9324
  scheduleQueueRegion: eu-west-2
  scheduleCreateQueue: false

postgresUsername: postgres@mine-support2
postgresPassword: changeme
postgresDatabase: mine_claims
# postgresHost is the host name of the PostgreSQL service
postgresHost: ffc-demo-claims-postgres
# postgresExternalName is the external host name to which PostgreSQL
# requests should be forwarded. If empty, PostgreSQL is assumed to be
# within the cluster and accessible via postgresHost
postgresExternalName:
postgresPort: 5432
  
livenessProbe:
  path: /healthz
  port: 3003
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3003
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
