apiVersion: v1
kind: Service
metadata:
  labels:
    app.component: claim-service
  name: claim-service
spec:
  ports:
  - name: http
    port: 3003
    targetPort: 3003
  selector:
    app.component: claim-service
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.component: claim-service
  name: claim-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app.component: claim-service
    spec:
      containers:   
      - name: mine-support-claim-service
        image: mine-support-claim-service
        imagePullPolicy: Never
        ports:
        - containerPort: 3003               
      restartPolicy: Always
status: {}
