- key: NODE_ENV
  value: "production"
- key: APPINSIGHTS_CONSOLE_DEBUG_ENABLED
  value: "true"
- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}"  
- key: CLAIM_QUEUE_ADDRESS
  value: "ffc-demo-claim" 
- key: CALCULATION_QUEUE_ADDRESS
  value: "ffc-demo-calculation"
- key: SCHEDULE_TOPIC_ADDRESS
  value: "ffc-demo-schedule"    
- key: POSTGRES_PORT
  value: "5432"        
- key: POSTGRES_SCHEMA_NAME
  value: "public" 
- key: NOTIFY_API_KEY
  value: "{{servicename}}-notify-api-key" 
  type: "keyvault"