- key: MESSAGE_QUEUE_HOST
  value: "DEVADPINFSB1401.servicebus.windows.net" 
- key: POSTGRES_HOST
  value: "devadpdbsps1401.postgres.database.azure.com"
- key: POSTGRES_USERNAME
  value: "devadpinfmi1401-ffc-demo-claim-service" 
- key: NOTIFY_EMAIL_TEMPLATE_KEY
  value: "c048c3e6-d189-45c2-bdf4-ee4a7a732167" 
- key: POSTGRES_DB
  value: "fcp-demo-claim"