- key: NODE_ENV
  value: "production"
- key: APPINSIGHTS_CONSOLE_DEBUG_ENABLED
  value: "true"
- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}"  
- key: CLAIM_QUEUE_ADDRESS
  value: "ffc-demo-claim" 
- key: CALCULATION_QUEUE_ADDRESS
  value: "ffc-demo-calculation"
- key: SCHEDULE_TOPIC_ADDRESS
  value: "ffc-demo-schedule"    
- key: MESSAGE_QUEUE_HOST
  value: "SNDADPINFSB1401.servicebus.windows.net"  
- key: POSTGRES_DB
  value: "ffc-demo-claim"
- key: POSTGRES_HOST
  value: "sndadpdbsps1401.postgres.database.azure.com"    
- key: POSTGRES_PORT
  value: "5432"        
- key: POSTGRES_SCHEMA_NAME
  value: "public"        
- key: APPINSIGHTS_INSTRUMENTATIONKEY
  value: "36932cc4-12b7-4f0f-bbee-36ba20174390"        
- key: POSTGRES_USERNAME
  value: "sndadpinfmid1401-ffc-demo-services" 
- key: NOTIFY_EMAIL_TEMPLATE_KEY
  value: "c048c3e6-d189-45c2-bdf4-ee4a7a732167" 
- key: NOTIFY_API_KEY
  value: "{{servicename}}-notify-api-key" 
  type: "keyvault"