#!/usr/bin/env sh

## DEPRECATED connected-start
## This script should be removed once the development repo has been
## updated to use `scripts/start --link`.

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

(
  cd "${projectRoot}"
  scripts/stop --link $@
)
