#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

(
  cd "${projectRoot}"

  helm upgrade ffc-demo-claim-service --install --namespace ffc-demo-claim-service ./helm
)
