#!/usr/bin/env sh

## Exec script
## Execute a given command in the main service container.
## If the service container is not running, this script will start and
## stop it either side of running the command.

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

# Set expected prefix for Docker resource names managed by this script
dockerPrefix="ffc-demo-claim"

(
  cd "${projectRoot}"

  existingService="$( docker ps -q --filter name=^${dockerPrefix}-service$ )"
  existingVolumes="$( docker volume ls --filter name=^${dockerPrefix}-service --format={{.Name}} )"

  if [ -z "${existingService}" ]; then
    printf "\nCreating service to execute command in.\n"
    docker-compose up --detach
  fi

  printf "\nExecuting command in ${dockerPrefix}-service:\n"
  echo "$@"

  docker-compose exec ${dockerPrefix}-service $@

  printf "\nCommand completed.\n"

  if [ -z "${existingService}" ]; then
    if [ -z "${existingVolumes}" ]; then
      printf "\nRemoving created service and volumes.\n"
      docker-compose down --volumes
    else
      printf "\nRemoving created service (leaving volumes as some existed already).\n"
      docker-compose down
    fi
  fi
)
