#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

# Check whether mine-support network needs creating
if [ -z "$(docker network ls --filter name=^mine-support$ --format={{.Name}})" ]; then
  echo "Creating mine-support network"
  docker network create mine-support
fi

(
  cd "${projectRoot}"
  docker-compose up --force-recreate $@
)
