#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

command="$@"
service="ffc-demo-claim-service"

compose() {
  docker-compose \
    -f docker-compose.yaml \
    -p "${service}-test" \
    $@
}

(
  cd "${projectRoot}"

  # Guarantee clean environment
  compose down -v
  docker-compose -f docker-compose.migrate.yaml -p "${service}-test" down -v

  # Ensure container images are up to date
  compose build
  docker-compose -f docker-compose.migrate.yaml -p "${service}-test" run --rm database-up

  # Run tests
  compose run ${service} ${command}

  # Clean up
  compose down --volumes
)
