#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

(
  cd "${projectRoot}"

  docker-compose \
    -f docker-compose.yaml \
    -f docker-compose.override.yaml \
    -f docker-compose.test.yaml \
    run mine-support-claim-service $@

  docker-compose \
    -f docker-compose.yaml \
    -f docker-compose.override.yaml \
    -f docker-compose.test.yaml \
     down -v
)
