environment: development
postgresUsername: postgres@mine-support2
postgresPassword: changeme
postgresDatabase: mine_claims
postgresHost:  mine-support-postgres-claims
postgresExternalName: host.docker.internal
postgresPort: 5432
name: mine-support-claim-service
image: mine-support-claim-service
service:
  type: ClusterIP
  port: 80
container:
  imagePullPolicy: IfNotPresent
  redeployOnChange: update this field to force a change
  requestMemory: 30Mi
  requestCpu: 30m
  limitMemory: 60Mi
  limitCpu: 60m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  restartPolicy: Always
  command: ["/bin/sh","-c"]
  args: ["npm run migrate; node index"]
  messageQueueHost: mine-support-artemis
  messageQueuePort: 5672
  messageQueueTransport: tcp
  calculationQueueAddress: calculation
  calculationQueueUser: artemis
  calculationQueuePassword: artemis
  scheduleQueueAddress: schedule
  scheduleQueueUser: artemis
  scheduleQueuePassword: artemis
replicaCount: 1
minReadySeconds: 10
maxSurge: 1
maxUnavailable: 1
