environment: development
containers:
  service:
    name: mine-support-claim-service
    port: 3003
    registry:
    image: mine-support-claim-service
    tag: latest
    imagePullPolicy: IfNotPresent
    requestMemory: 30Mi
    requestCpu: 10m
    limitMemory: 60Mi
    limitCpu: 40m
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    restartPolicy: Always   
    messageQueue: amqp://mine-support-message-service
database:
  name: mine-support-postgres-claims
  externalName: host.docker.internal
  port: 5432   
messageQueue:
  name: mine-support-message-service
  externalName: host.docker.internal
  port: 5672
replicas: 1
minReadySeconds: 10
maxSurge: 1
maxUnavailable: 1
